FROM nginx
RUN rm /etc/nginx/conf.d/default.conf
COPY nginx.conf /etc/nginx/conf.d/default.conf
# FROM imkulikov/nginx-sticky
# RUN rm /etc/nginx/conf.d/03-default.conf
# COPY nginx.conf /etc/nginx/conf.d/03-default.conf